2025-03-09 22:39:15,659 INFO    Thread-11 (_run_job):20344 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\prajv\Downloads\ass1\DA6401_ASSIGNMENT1\wandb\run-20250309_223915-scgl2ag0\logs\debug.log
2025-03-09 22:39:15,660 INFO    Thread-11 (_run_job):20344 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\prajv\Downloads\ass1\DA6401_ASSIGNMENT1\wandb\run-20250309_223915-scgl2ag0\logs\debug-internal.log
2025-03-09 22:39:15,660 INFO    Thread-11 (_run_job):20344 [wandb_init.py:init():761] calling init triggers
2025-03-09 22:39:15,660 INFO    Thread-11 (_run_job):20344 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activationFunc': 'relu', 'batchSize': 116, 'hiddenLayer_Size': 128, 'learningRate': 0.0001, 'num_epochs': 20, 'num_hiddenLayers': 4, 'optimizer': 'momentum', 'weightDecay': 0, 'weightInit': 'xavier'}
config: {'num_epochs': 10, 'num_hiddenLayers': 3, 'hiddenLayer_Size': 40, 'weightDecay': 0, 'learningRate': 0.001, 'optimizer': 'Nesterov_Accelerated_GD', 'batchSize': 32, 'weightInit': 'xavier', 'activationFunc': 'sigmoid', '_wandb': {}}
2025-03-09 22:39:15,660 INFO    Thread-11 (_run_job):20344 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-09 22:39:15,839 INFO    Thread-11 (_run_job):20344 [wandb_run.py:_finish():2112] finishing run da6401-assignments/assignment1/scgl2ag0
2025-03-09 22:39:15,841 ERROR   Thread-11 (_run_job):20344 [jupyter.py:save_history():450] Run pip install nbformat to save notebook history
2025-03-09 22:39:15,841 INFO    Thread-11 (_run_job):20344 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-09 22:39:15,841 INFO    Thread-11 (_run_job):20344 [wandb_init.py:_jupyter_teardown():581] cleaning up jupyter logic
2025-03-09 22:39:15,841 INFO    Thread-11 (_run_job):20344 [wandb_run.py:_atexit_cleanup():2340] got exitcode: 1
2025-03-09 22:39:15,841 INFO    Thread-11 (_run_job):20344 [wandb_run.py:_restore():2322] restore
2025-03-09 22:39:15,841 INFO    Thread-11 (_run_job):20344 [wandb_run.py:_restore():2328] restore done
2025-03-09 22:39:18,011 INFO    Thread-11 (_run_job):20344 [wandb_run.py:_footer_history_summary_info():3956] rendering history
2025-03-09 22:39:18,011 INFO    Thread-11 (_run_job):20344 [wandb_run.py:_footer_history_summary_info():3988] rendering summary
2025-03-09 22:39:18,011 INFO    Thread-11 (_run_job):20344 [wandb_run.py:_footer_sync_info():3917] logging synced files
2025-03-09 22:39:18,017 ERROR   MainThread:20344 [pyagent.py:_run_jobs_from_queue():234] Run scgl2ag0 errored:
Traceback (most recent call last):
  File "c:\Python312\Lib\site-packages\wandb\agents\pyagent.py", line 306, in _run_job
    self._function()
  File "C:\Users\prajv\AppData\Local\Temp\ipykernel_20344\1058529509.py", line 36, in sweep_hyperParameters
    model.train(x_train, y_train, x_val, y_val, num_epochs, learningRate, optimizer, batchSize)
  File "C:\Users\prajv\AppData\Local\Temp\ipykernel_20344\288938270.py", line 61, in train
    self.backpropagation(x_batch, y_batch, learning_rate, optimizer)
  File "C:\Users\prajv\AppData\Local\Temp\ipykernel_20344\288938270.py", line 139, in backpropagation
    dw = deltas[i].dot(self.layers[i]) / m
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: shapes (128,116) and (784,116) not aligned: 116 (dim 1) != 784 (dim 0)

2025-03-09 22:39:23,060 INFO    MsgRouterThr:20344 [mailbox.py:close():129] Closing mailbox, abandoning 1 handles.
2025-03-09 22:39:24,051 INFO    Thread-16 (_run_job):20344 [wandb_setup.py:_flush():67] Current SDK version is 0.19.8
2025-03-09 22:39:24,052 INFO    Thread-16 (_run_job):20344 [wandb_setup.py:_flush():67] Configure stats pid to 20344
2025-03-09 22:39:24,052 INFO    Thread-16 (_run_job):20344 [wandb_setup.py:_flush():67] Loading settings from C:\Users\prajv\.config\wandb\settings
2025-03-09 22:39:24,052 INFO    Thread-16 (_run_job):20344 [wandb_setup.py:_flush():67] Loading settings from c:\Users\prajv\Downloads\ass1\DA6401_ASSIGNMENT1\wandb\settings
2025-03-09 22:39:24,052 INFO    Thread-16 (_run_job):20344 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-09 22:39:24,053 INFO    Thread-16 (_run_job):20344 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\prajv\Downloads\ass1\DA6401_ASSIGNMENT1\wandb\run-20250309_223924-t0wrc7bt\logs\debug.log
2025-03-09 22:39:24,053 INFO    Thread-16 (_run_job):20344 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\prajv\Downloads\ass1\DA6401_ASSIGNMENT1\wandb\run-20250309_223924-t0wrc7bt\logs\debug-internal.log
2025-03-09 22:39:24,053 INFO    Thread-16 (_run_job):20344 [wandb_init.py:monkeypatch_ipython():599] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000001E5BD7B2F60>
2025-03-09 22:39:24,053 INFO    Thread-16 (_run_job):20344 [wandb_init.py:init():761] calling init triggers
2025-03-09 22:39:24,053 INFO    Thread-16 (_run_job):20344 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activationFunc': 'tanh', 'batchSize': 164, 'hiddenLayer_Size': 64, 'learningRate': 0.0001, 'num_epochs': 20, 'num_hiddenLayers': 4, 'optimizer': 'sgd', 'weightDecay': 0.5, 'weightInit': 'xavier'}
config: {'_wandb': {}}
2025-03-09 22:39:24,053 INFO    Thread-16 (_run_job):20344 [wandb_init.py:init():784] starting backend
2025-03-09 22:39:24,053 INFO    Thread-16 (_run_job):20344 [wandb_init.py:init():788] sending inform_init request
2025-03-09 22:39:24,053 INFO    Thread-16 (_run_job):20344 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=spawn, using: spawn
2025-03-09 22:39:24,056 INFO    Thread-16 (_run_job):20344 [wandb_init.py:init():798] backend started and connected
2025-03-09 22:39:24,057 INFO    Thread-16 (_run_job):20344 [wandb_run.py:_config_callback():1261] config_cb None None {'activationFunc': 'tanh', 'batchSize': 164, 'hiddenLayer_Size': 64, 'learningRate': 0.0001, 'num_epochs': 20, 'num_hiddenLayers': 4, 'optimizer': 'sgd', 'weightDecay': 0.5, 'weightInit': 'xavier'}
2025-03-09 22:39:24,060 INFO    Thread-16 (_run_job):20344 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2025-03-09 22:39:24,078 INFO    Thread-16 (_run_job):20344 [wandb_init.py:init():891] updated telemetry
2025-03-09 22:39:24,140 INFO    Thread-16 (_run_job):20344 [wandb_init.py:init():915] communicating run to backend with 90.0 second timeout
2025-03-09 22:39:25,792 INFO    Thread-16 (_run_job):20344 [wandb_init.py:init():990] starting run threads in backend
2025-03-09 22:39:26,088 INFO    Thread-16 (_run_job):20344 [wandb_run.py:_console_start():2375] atexit reg
2025-03-09 22:39:26,089 INFO    Thread-16 (_run_job):20344 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-09 22:39:26,089 INFO    Thread-16 (_run_job):20344 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-09 22:39:26,089 INFO    Thread-16 (_run_job):20344 [wandb_run.py:_redirect():2315] Redirects installed.
2025-03-09 22:39:26,090 INFO    Thread-16 (_run_job):20344 [wandb_init.py:init():1032] run started, returning control to user process
2025-03-09 22:39:26,091 INFO    Thread-16 (_run_job):20344 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\prajv\Downloads\ass1\DA6401_ASSIGNMENT1\wandb\run-20250309_223926-t0wrc7bt\logs\debug.log
2025-03-09 22:39:26,091 INFO    Thread-16 (_run_job):20344 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\prajv\Downloads\ass1\DA6401_ASSIGNMENT1\wandb\run-20250309_223926-t0wrc7bt\logs\debug-internal.log
2025-03-09 22:39:26,091 INFO    Thread-16 (_run_job):20344 [wandb_init.py:init():761] calling init triggers
2025-03-09 22:39:26,091 INFO    Thread-16 (_run_job):20344 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activationFunc': 'tanh', 'batchSize': 164, 'hiddenLayer_Size': 64, 'learningRate': 0.0001, 'num_epochs': 20, 'num_hiddenLayers': 4, 'optimizer': 'sgd', 'weightDecay': 0.5, 'weightInit': 'xavier'}
config: {'num_epochs': 10, 'num_hiddenLayers': 3, 'hiddenLayer_Size': 40, 'weightDecay': 0, 'learningRate': 0.001, 'optimizer': 'Nesterov_Accelerated_GD', 'batchSize': 32, 'weightInit': 'xavier', 'activationFunc': 'sigmoid', '_wandb': {}}
2025-03-09 22:39:26,091 INFO    Thread-16 (_run_job):20344 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-09 22:39:26,248 INFO    Thread-16 (_run_job):20344 [wandb_run.py:_finish():2112] finishing run da6401-assignments/assignment1/t0wrc7bt
2025-03-09 22:39:26,250 ERROR   Thread-16 (_run_job):20344 [jupyter.py:save_history():450] Run pip install nbformat to save notebook history
2025-03-09 22:39:26,250 INFO    Thread-16 (_run_job):20344 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-09 22:39:26,250 INFO    Thread-16 (_run_job):20344 [wandb_init.py:_jupyter_teardown():581] cleaning up jupyter logic
2025-03-09 22:39:26,250 INFO    Thread-16 (_run_job):20344 [wandb_run.py:_atexit_cleanup():2340] got exitcode: 1
2025-03-09 22:39:26,250 INFO    Thread-16 (_run_job):20344 [wandb_run.py:_restore():2322] restore
2025-03-09 22:39:26,250 INFO    Thread-16 (_run_job):20344 [wandb_run.py:_restore():2328] restore done
2025-03-09 22:39:28,228 INFO    Thread-16 (_run_job):20344 [wandb_run.py:_footer_history_summary_info():3956] rendering history
2025-03-09 22:39:28,229 INFO    Thread-16 (_run_job):20344 [wandb_run.py:_footer_history_summary_info():3988] rendering summary
2025-03-09 22:39:28,229 INFO    Thread-16 (_run_job):20344 [wandb_run.py:_footer_sync_info():3917] logging synced files
2025-03-09 22:39:28,233 ERROR   MainThread:20344 [pyagent.py:_run_jobs_from_queue():234] Run t0wrc7bt errored:
Traceback (most recent call last):
  File "c:\Python312\Lib\site-packages\wandb\agents\pyagent.py", line 306, in _run_job
    self._function()
  File "C:\Users\prajv\AppData\Local\Temp\ipykernel_20344\1058529509.py", line 36, in sweep_hyperParameters
    model.train(x_train, y_train, x_val, y_val, num_epochs, learningRate, optimizer, batchSize)
  File "C:\Users\prajv\AppData\Local\Temp\ipykernel_20344\288938270.py", line 61, in train
    self.backpropagation(x_batch, y_batch, learning_rate, optimizer)
  File "C:\Users\prajv\AppData\Local\Temp\ipykernel_20344\288938270.py", line 139, in backpropagation
    dw = deltas[i].dot(self.layers[i]) / m
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: shapes (64,164) and (784,164) not aligned: 164 (dim 1) != 784 (dim 0)

2025-03-09 22:39:33,253 INFO    MsgRouterThr:20344 [mailbox.py:close():129] Closing mailbox, abandoning 1 handles.
2025-03-09 22:39:34,306 INFO    Thread-21 (_run_job):20344 [wandb_setup.py:_flush():67] Current SDK version is 0.19.8
2025-03-09 22:39:34,306 INFO    Thread-21 (_run_job):20344 [wandb_setup.py:_flush():67] Configure stats pid to 20344
2025-03-09 22:39:34,306 INFO    Thread-21 (_run_job):20344 [wandb_setup.py:_flush():67] Loading settings from C:\Users\prajv\.config\wandb\settings
2025-03-09 22:39:34,306 INFO    Thread-21 (_run_job):20344 [wandb_setup.py:_flush():67] Loading settings from c:\Users\prajv\Downloads\ass1\DA6401_ASSIGNMENT1\wandb\settings
2025-03-09 22:39:34,306 INFO    Thread-21 (_run_job):20344 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-09 22:39:34,306 INFO    Thread-21 (_run_job):20344 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\prajv\Downloads\ass1\DA6401_ASSIGNMENT1\wandb\run-20250309_223934-1hjgq1vl\logs\debug.log
2025-03-09 22:39:34,306 INFO    Thread-21 (_run_job):20344 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\prajv\Downloads\ass1\DA6401_ASSIGNMENT1\wandb\run-20250309_223934-1hjgq1vl\logs\debug-internal.log
2025-03-09 22:39:34,306 INFO    Thread-21 (_run_job):20344 [wandb_init.py:monkeypatch_ipython():599] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000001E5BD7B3680>
2025-03-09 22:39:34,315 INFO    Thread-21 (_run_job):20344 [wandb_init.py:init():761] calling init triggers
2025-03-09 22:39:34,315 INFO    Thread-21 (_run_job):20344 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activationFunc': 'tanh', 'batchSize': 164, 'hiddenLayer_Size': 64, 'learningRate': 0.0001, 'num_epochs': 5, 'num_hiddenLayers': 5, 'optimizer': 'momentum', 'weightDecay': 0.0005, 'weightInit': 'xavier'}
config: {'_wandb': {}}
2025-03-09 22:39:34,315 INFO    Thread-21 (_run_job):20344 [wandb_init.py:init():784] starting backend
2025-03-09 22:39:34,315 INFO    Thread-21 (_run_job):20344 [wandb_init.py:init():788] sending inform_init request
2025-03-09 22:39:34,322 INFO    Thread-21 (_run_job):20344 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=spawn, using: spawn
2025-03-09 22:39:34,322 INFO    Thread-21 (_run_job):20344 [wandb_init.py:init():798] backend started and connected
2025-03-09 22:39:34,324 INFO    Thread-21 (_run_job):20344 [wandb_run.py:_config_callback():1261] config_cb None None {'activationFunc': 'tanh', 'batchSize': 164, 'hiddenLayer_Size': 64, 'learningRate': 0.0001, 'num_epochs': 5, 'num_hiddenLayers': 5, 'optimizer': 'momentum', 'weightDecay': 0.0005, 'weightInit': 'xavier'}
2025-03-09 22:39:34,326 INFO    Thread-21 (_run_job):20344 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2025-03-09 22:39:34,345 INFO    Thread-21 (_run_job):20344 [wandb_init.py:init():891] updated telemetry
2025-03-09 22:39:34,396 INFO    Thread-21 (_run_job):20344 [wandb_init.py:init():915] communicating run to backend with 90.0 second timeout
2025-03-09 22:39:36,127 INFO    Thread-21 (_run_job):20344 [wandb_init.py:init():990] starting run threads in backend
2025-03-09 22:39:36,417 INFO    Thread-21 (_run_job):20344 [wandb_run.py:_console_start():2375] atexit reg
2025-03-09 22:39:36,417 INFO    Thread-21 (_run_job):20344 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-09 22:39:36,418 INFO    Thread-21 (_run_job):20344 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-09 22:39:36,418 INFO    Thread-21 (_run_job):20344 [wandb_run.py:_redirect():2315] Redirects installed.
2025-03-09 22:39:36,420 INFO    Thread-21 (_run_job):20344 [wandb_init.py:init():1032] run started, returning control to user process
2025-03-09 22:39:36,424 INFO    Thread-21 (_run_job):20344 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\prajv\Downloads\ass1\DA6401_ASSIGNMENT1\wandb\run-20250309_223936-1hjgq1vl\logs\debug.log
2025-03-09 22:39:36,424 INFO    Thread-21 (_run_job):20344 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\prajv\Downloads\ass1\DA6401_ASSIGNMENT1\wandb\run-20250309_223936-1hjgq1vl\logs\debug-internal.log
2025-03-09 22:39:36,424 INFO    Thread-21 (_run_job):20344 [wandb_init.py:init():761] calling init triggers
2025-03-09 22:39:36,424 INFO    Thread-21 (_run_job):20344 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activationFunc': 'tanh', 'batchSize': 164, 'hiddenLayer_Size': 64, 'learningRate': 0.0001, 'num_epochs': 5, 'num_hiddenLayers': 5, 'optimizer': 'momentum', 'weightDecay': 0.0005, 'weightInit': 'xavier'}
config: {'num_epochs': 10, 'num_hiddenLayers': 3, 'hiddenLayer_Size': 40, 'weightDecay': 0, 'learningRate': 0.001, 'optimizer': 'Nesterov_Accelerated_GD', 'batchSize': 32, 'weightInit': 'xavier', 'activationFunc': 'sigmoid', '_wandb': {}}
2025-03-09 22:39:36,424 INFO    Thread-21 (_run_job):20344 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-09 22:39:36,621 INFO    Thread-21 (_run_job):20344 [wandb_run.py:_finish():2112] finishing run da6401-assignments/assignment1/1hjgq1vl
2025-03-09 22:39:36,623 ERROR   Thread-21 (_run_job):20344 [jupyter.py:save_history():450] Run pip install nbformat to save notebook history
2025-03-09 22:39:36,624 INFO    Thread-21 (_run_job):20344 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-09 22:39:36,624 INFO    Thread-21 (_run_job):20344 [wandb_init.py:_jupyter_teardown():581] cleaning up jupyter logic
2025-03-09 22:39:36,624 INFO    Thread-21 (_run_job):20344 [wandb_run.py:_atexit_cleanup():2340] got exitcode: 1
2025-03-09 22:39:36,624 INFO    Thread-21 (_run_job):20344 [wandb_run.py:_restore():2322] restore
2025-03-09 22:39:36,624 INFO    Thread-21 (_run_job):20344 [wandb_run.py:_restore():2328] restore done
2025-03-09 22:39:39,309 INFO    Thread-21 (_run_job):20344 [wandb_run.py:_footer_history_summary_info():3956] rendering history
2025-03-09 22:39:39,309 INFO    Thread-21 (_run_job):20344 [wandb_run.py:_footer_history_summary_info():3988] rendering summary
2025-03-09 22:39:39,309 INFO    Thread-21 (_run_job):20344 [wandb_run.py:_footer_sync_info():3917] logging synced files
2025-03-09 22:39:39,314 ERROR   MainThread:20344 [pyagent.py:_run_jobs_from_queue():234] Run 1hjgq1vl errored:
Traceback (most recent call last):
  File "c:\Python312\Lib\site-packages\wandb\agents\pyagent.py", line 306, in _run_job
    self._function()
  File "C:\Users\prajv\AppData\Local\Temp\ipykernel_20344\1058529509.py", line 36, in sweep_hyperParameters
    model.train(x_train, y_train, x_val, y_val, num_epochs, learningRate, optimizer, batchSize)
  File "C:\Users\prajv\AppData\Local\Temp\ipykernel_20344\288938270.py", line 61, in train
    self.backpropagation(x_batch, y_batch, learning_rate, optimizer)
  File "C:\Users\prajv\AppData\Local\Temp\ipykernel_20344\288938270.py", line 139, in backpropagation
    dw = deltas[i].dot(self.layers[i]) / m
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: shapes (64,164) and (784,164) not aligned: 164 (dim 1) != 784 (dim 0)

2025-03-09 22:39:39,314 ERROR   MainThread:20344 [pyagent.py:_run_jobs_from_queue():245] Detected 3 failed runs in the first 60 seconds, killing sweep.
